"""Generate a weekly business review."""

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

from reportmail import KPI, Chart, Report, Table, Text

sales = pd.DataFrame(
    {
        "Region": ["East", "West", "North", "South"],
        "Revenue": [120_000, 98_000, 76_000, 64_000],
        "Orders": [580, 491, 402, 369],
    }
)
figure, axis = plt.subplots(figsize=(8, 4))
axis.bar(sales["Region"], sales["Revenue"], color="#2563eb")
axis.set_title("Revenue by region")
axis.set_ylabel("Revenue (INR)")
figure.tight_layout()

report = Report(
    "Weekly Business Review",
    subtitle="Week ending 14 July 2026",
    preheader="Revenue increased 8.2% this week.",
    footer="Generated by reportmail",
).add(
    KPI(
        "Revenue",
        1_240_000,
        format="currency",
        currency="INR",
        change=0.082,
        change_format="percent",
        trend="up",
    ),
    KPI("Orders", 1_842, format="integer", change=0.041, change_format="percent", trend="up"),
    KPI(
        "Refund rate", 0.018, format="percent", change=-0.003, change_format="percent", trend="down"
    ),
    Chart(figure, title="Regional revenue", alt="Bar chart showing revenue by region", close=True),
    Table(
        sales,
        title="Regional performance",
        formats={"Revenue": "currency", "Orders": "integer"},
        currency="INR",
    ),
    Text("Revenue and order volume improved across the two strongest regions.", title="Summary"),
)

output = report.save(Path(__file__).with_suffix(".html"))
print(f"Wrote {output}")
